### ISSUE TITLE
Quic-wf-core.tgz is not downloadable

### ISSUE THREAD

**Issue by cccccchengjialin** [jpcsmith/wf-in-the-age-of-quic#1]
Hello author, I am very interested in your work. Can you provide a new download address for the dataset? I would greatly appreciate it if you could receive a response

**Comment by jpcsmith** [comment]
Sorry for that, the link has been updated. You can find the tar files here: https://doi.org/10.3929/ethz-b-000456101

**Comment by cccccchengjialin** [comment]
Thank you very much for your update!




养乐多?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jpcsmith/wf-in-the-age-of-quic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月12日(星期三) 晚上11:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jpcsmith/wf-in-the-age-of-quic] Quic-wf-core.tgz is not downloadable (Issue #1)





 
Sorry for that, the link has been updated. You can find the tar files here: https://doi.org/10.3929/ethz-b-000456101
